=== VISHAL-A-S/Ananda-Bakery-MEAN/xml-dtd-xsd-json/index.xsd
<?xml version="1.0"?>  
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.index.com"
xmlns="http://www.index.com"
elementFormDefault="qualified">
<xs:element name="Login">  
  <xs:complexType>
    <xs:sequence>
        <xs:element name="User"  minOccurs="0" maxOccurs="unbounded">
            <xs:complexType>
                <xs:all>
                  <xs:element name="Email">
                    <xs:simpleType>
                      <xs:restriction base="xs:string">
                        <xs:pattern value="[a-zA-Z0-9+_.-]+@[a-zA-Z0-9.-]+"></xs:pattern>
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:element>
                  <xs:element name="Password">
                    <xs:simpleType>
                      <xs:restriction base="xs:string">
                        <xs:pattern value="[A-Za-z0-9#?!@$%^*-].{6,}"></xs:pattern>
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:element>
                </xs:all>
                <xs:attribute name="id" type="xs:ID"/>
            </xs:complexType>
        </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>   
</xs:schema>

=== VISHAL-A-S/Ananda-Bakery-MEAN/xml-dtd-xsd-json/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- IMPLICIT DTD -->
<!DOCTYPE Login [
<!ELEMENT Login (User+)>
<!ELEMENT User (Email,Password)>
<!ELEMENT Email (#PCDATA)>
<!ELEMENT Password (#PCDATA)>
<!ATTLIST User id ID (#REQUIRED)>
]>
<!-- 
EXPLICIT DTD
<!DOCTYPE Login SYSTEM "index.dtd"> 
-->
<Login xmlns="http://www.index.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.index.com index.xsd">
    <User id="vishal872002">
        <Email>vishal872002@gmail.com</Email>
        <Password>Password123</Password>
    </User>
    <User id="vishal123">
        <Email>vishal123@gmail.com</Email>
        <Password>Password012</Password>
    </User>
    <User id="vishal12345">
        <Email>vishal12345@gmail.com</Email>
        <Password>PassWord</Password>
    </User>
</Login>
